#!/usr/bin/env bash

if [ ! -x "$(convert -version)" ]; then
  echo "Installing Docker"
else
  echo "Docker installed skipping"
fi

if [ ! "$(convert -version)" &> /dev/null ]; then
  echo "Installing Imagemagic"
else
  echo "Imagemagic installed skipping"
fi
